# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0013_postmalllink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='방송 제목')),
                ('description', models.TextField(blank=True, verbose_name='방송 설명')),
                ('live_url', models.URLField(blank=True, max_length=500, verbose_name='외부 라이브 URL')),
                ('embed_url', models.URLField(blank=True, max_length=500, verbose_name='임베드 URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live/thumbnails/', verbose_name='썸네일')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('live', '라이브'), ('ended', '종료'), ('hidden', '숨김')], default='scheduled', max_length=20, verbose_name='방송 상태')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 예정 시간')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='실제 시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('chat_enabled', models.BooleanField(default=True, verbose_name='채팅 사용')),
                ('guest_view_allowed', models.BooleanField(default=True, verbose_name='비로그인 시청 허용')),
                ('is_visible', models.BooleanField(default=True, verbose_name='목록 노출')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_rooms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_live_rooms', to=settings.AUTH_USER_MODEL, verbose_name='방송 주인(판매자)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_live_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '라이브 방송',
                'verbose_name_plural': '라이브 방송',
                'ordering': ['-sort_order', '-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='숨김')),
                ('hidden_reason', models.CharField(blank=True, max_length=200, verbose_name='숨김 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('live_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.liveroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '라이브 채팅 메시지',
                'verbose_name_plural': '라이브 채팅 메시지',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveRoomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='표시 상품명')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='표시 가격')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='표시 이미지 URL')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='외부 구매 링크')),
                ('is_featured', models.BooleanField(default=False, verbose_name='현재 소개중')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='live.liveroom')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_room_products', to='boards.post')),
            ],
            options={
                'verbose_name': '방송 연결 상품',
                'verbose_name_plural': '방송 연결 상품',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
