# Generated by Django 5.2.12 on 2026-03-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='가격')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('status', models.CharField(choices=[('onsale', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='onsale', max_length=20, verbose_name='거래 상태')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='가격 흥정 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='구매 요청 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='marketplace.marketplaceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'buyer')},
            },
        ),
    ]
