# Generated by Django 5.2.12 on 2026-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplacecategory_marketplaceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
