# Generated by Django 5.2.12 on 2026-04-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_homeproductsectionconfig'),
        ('marketplace', '0004_marketplaceitem_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='external_image_url',
            field=models.URLField(blank=True, verbose_name='외부 이미지 URL'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='외부 원본 메타'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='external_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='catalog.externalprovider'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='외부 참조값'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='option_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='선택 옵션 스냅샷'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='source_mode',
            field=models.CharField(choices=[('manual', '수동 등록'), ('imported', '외부 불러오기')], default='manual', max_length=20, verbose_name='등록 방식'),
        ),
    ]
