# Generated by Django 5.2.12 on 2026-04-08 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_marketplaceitem_external_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='approval_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='승인 메모'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', '검토중'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 시각'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_market_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
