# Generated by Django 5.2.12 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_marketplaceitem_approval_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacecategory",
            name="menu_placement",
            field=models.CharField(
                choices=[
                    ("sale", "판매상품"),
                    ("used", "중고상품"),
                    ("both", "둘 다 노출"),
                    ("hidden", "노출 안 함"),
                ],
                default="used",
                max_length=10,
                verbose_name="메뉴 노출 위치",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceitem",
            name="menu_placement",
            field=models.CharField(
                choices=[
                    ("sale", "판매상품"),
                    ("used", "중고상품"),
                ],
                default="used",
                max_length=10,
                verbose_name="메뉴 노출 위치",
            ),
        ),
    ]
