# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_add_menu_placement_fields_to_marketplace_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceitem",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="원래가격",
            ),
        ),
    ]
