# Generated by Django 5.2.12 on 2026-03-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_notice', 'notice_order', '-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='board',
            name='allow_anonymous',
            field=models.BooleanField(default=True, verbose_name='비회원 읽기 허용'),
        ),
        migrations.AddField(
            model_name='board',
            name='allow_anonymous_post',
            field=models.BooleanField(default=False, verbose_name='익명글 허용'),
        ),
        migrations.AddField(
            model_name='board',
            name='allow_file_upload',
            field=models.BooleanField(default=True, verbose_name='파일 첨부 허용'),
        ),
        migrations.AddField(
            model_name='board',
            name='comment_grade',
            field=models.CharField(default='member', max_length=20, verbose_name='댓글 최소 등급'),
        ),
        migrations.AddField(
            model_name='board',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='게시판 아이콘'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AddField(
            model_name='board',
            name='min_grade',
            field=models.CharField(default='seed', max_length=20, verbose_name='읽기 최소 등급'),
        ),
        migrations.AddField(
            model_name='board',
            name='read_permission',
            field=models.CharField(choices=[('public', '전체공개'), ('member', '회원전용'), ('grade', '등급제한')], default='public', max_length=20, verbose_name='읽기 권한'),
        ),
        migrations.AddField(
            model_name='board',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.AddField(
            model_name='board',
            name='use_category',
            field=models.BooleanField(default=False, verbose_name='말머리 사용'),
        ),
        migrations.AddField(
            model_name='board',
            name='write_grade',
            field=models.CharField(default='member', max_length=20, verbose_name='쓰기 최소 등급'),
        ),
        migrations.AddField(
            model_name='post',
            name='blind_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='블라인드 사유'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_blinded',
            field=models.BooleanField(default=False, verbose_name='블라인드 여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='임시 삭제 여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='공지 여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='moved_from_board_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='이동 전 게시판명'),
        ),
        migrations.AddField(
            model_name='post',
            name='notice_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='공지 종료일'),
        ),
        migrations.AddField(
            model_name='post',
            name='notice_order',
            field=models.PositiveIntegerField(default=0, verbose_name='공지 정렬 순서'),
        ),
        migrations.AddField(
            model_name='post',
            name='notice_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='공지 시작일'),
        ),
        migrations.AddField(
            model_name='post',
            name='notice_type',
            field=models.CharField(blank=True, choices=[('global', '전체공지'), ('board', '게시판공지')], max_length=20, verbose_name='공지 타입'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('general', '일반'), ('hotdeal', '핫딜'), ('marketplace', '중고장터'), ('notice', '공지')], default='general', max_length=20, verbose_name='게시판 종류'),
        ),
    ]
