# Generated by Django 5.2.12 on 2026-03-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '스팸/광고'), ('abuse', '욕설/비방'), ('adult', '음란물'), ('private', '개인정보'), ('copyright', '저작권'), ('other', '기타')], max_length=20, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, verbose_name='신고 상세')),
                ('status', models.CharField(choices=[('pending', '처리대기'), ('resolved', '처리완료'), ('dismissed', '기각')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('handled_note', models.TextField(blank=True, verbose_name='처리 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='boards.comment')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='boards.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
    ]
