# Generated by Django 5.2.12 on 2026-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='키워드')),
                ('filter_type', models.CharField(choices=[('exact', '완전일치'), ('contains', '포함'), ('regex', '정규식')], default='contains', max_length=20, verbose_name='필터 타입')),
                ('action', models.CharField(choices=[('block', '게시 차단'), ('replace', '치환'), ('flag', '검토 필요')], default='block', max_length=20, verbose_name='처리 방식')),
                ('target', models.CharField(choices=[('all', '전체'), ('post', '게시글'), ('comment', '댓글'), ('nickname', '닉네임')], default='all', max_length=20, verbose_name='대상')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
