# Generated by Django 5.2.12 on 2026-03-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_keywordfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='audience',
            field=models.CharField(choices=[('all', '공통'), ('buyer', '구매자'), ('seller', '판매자')], default='all', max_length=20, verbose_name='대상 회원'),
        ),
        migrations.AddField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boards.board'),
        ),
        migrations.AddField(
            model_name='board',
            name='show_in_top_menu',
            field=models.BooleanField(default=False, verbose_name='탑 메뉴 노출 여부'),
        ),
    ]
