# Generated by Django 5.2.13 on 2026-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_audience_board_parent_board_show_in_top_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='비밀댓글 여부'),
        ),
    ]
