# Generated by Django 5.2.15 on 2026-06-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_backfill_short_link_store_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMallLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(blank=True, max_length=80, verbose_name='쇼핑몰명')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='상품명')),
                ('product_url', models.URLField(max_length=500, verbose_name='상품 URL')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='대표 이미지 URL')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='원래가격')),
                ('current_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='현재가격')),
                ('discount_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='할인율(%)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_links', to='boards.post')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
