# Generated by Django 5.2.12 on 2026-03-10 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', '댓글'), ('like', '추천'), ('message', '쪽지'), ('purchase', '구매요청')], max_length=20, verbose_name='알림 종류')),
                ('title', models.CharField(max_length=120, verbose_name='알림 제목')),
                ('message', models.TextField(verbose_name='알림 내용')),
                ('target_url', models.CharField(blank=True, max_length=255, verbose_name='이동 경로')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
    ]
