# Generated by Django 5.2.12 on 2026-03-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', '내부 알림'), ('email', '이메일'), ('kakao', '카카오톡'), ('sms', '문자')], max_length=20, verbose_name='발송 채널')),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '발송완료'), ('failed', '실패'), ('skipped', '건너뜀')], default='pending', max_length=20, verbose_name='발송 상태')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='발송 대상')),
                ('provider', models.CharField(blank=True, max_length=120, verbose_name='발송 제공자')),
                ('response_code', models.CharField(blank=True, max_length=120, verbose_name='응답 코드')),
                ('response_message', models.TextField(blank=True, verbose_name='응답 메시지')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='중복 방지 키')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_in_app', models.BooleanField(default=True, verbose_name='내부 알림 허용')),
                ('allow_email', models.BooleanField(default=False, verbose_name='이메일 허용')),
                ('allow_kakao', models.BooleanField(default=False, verbose_name='카카오 허용')),
                ('allow_sms', models.BooleanField(default=False, verbose_name='문자 허용')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='수신 이메일')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='수신 번호')),
                ('kakao_target', models.CharField(blank=True, max_length=120, verbose_name='카카오 식별값')),
                ('quiet_hours_start', models.PositiveSmallIntegerField(default=23, verbose_name='야간 시작 시')),
                ('quiet_hours_end', models.PositiveSmallIntegerField(default=8, verbose_name='야간 종료 시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
