from django.urls import path

from .views import (
    AdminCategoryFilterDetailView,
    AdminCategoryFilterListCreateView,
    AdminCategoryFilterOptionDetailView,
    AdminCategoryFilterOptionListCreateView,
    AdminCategoryReferenceImageDetailView,
    AdminCategoryReferenceImageListCreateView,
    AdminCategoryMappingDetailView,
    AdminCategoryMappingListCreateView,
    HomeProductSectionConfigListView,
    AdminHomeProductSectionConfigDetailView,
    AdminHomeProductSectionConfigListCreateView,
    AdminSiteDisplaySettingView,
    AdminExternalAttributeListCreateView,
    AdminExternalCategoryListCreateView,
    AdminFilterMappingDetailView,
    AdminFilterMappingListCreateView,
    AdminProductCategoryDetailView,
    AdminProductCategoryListCreateView,
    AdminProviderDetailView,
    AdminProviderListCreateView,
    ExternalProviderListView,
    ProductAlertSubscriptionDetailView,
    ProductAlertSubscriptionListCreateView,
    ProductAlertSubscriptionMatchListView,
    ProductCategoryListView,
    SiteDisplaySettingView,
    SellerOptionPresetDetailView,
    SellerOptionPresetListCreateView,
    SellerImportPreviewView,
    AdminHomeHeroSlideDetailView,
    AdminHomeHeroSlideListCreateView,
    HomeHeroSlideListView,
    AdminHomeHeroSlideReorderView,
)

urlpatterns = [
    path("catalog/categories/", ProductCategoryListView.as_view(), name="catalog_category_list"),
    path("catalog/site-settings/", SiteDisplaySettingView.as_view(), name="catalog_site_settings"),
    path("catalog/providers/", ExternalProviderListView.as_view(), name="catalog_provider_list"),
    path("catalog/home-sections/", HomeProductSectionConfigListView.as_view(), name="catalog_home_section_list"),
    path("catalog/import-preview/", SellerImportPreviewView.as_view(), name="catalog_import_preview"),
    path("catalog/subscriptions/", ProductAlertSubscriptionListCreateView.as_view(), name="catalog_subscription_list_create"),
    path("catalog/subscriptions/<int:subscription_id>/", ProductAlertSubscriptionDetailView.as_view(), name="catalog_subscription_detail"),
    path("catalog/subscriptions/matches/", ProductAlertSubscriptionMatchListView.as_view(), name="catalog_subscription_matches"),
    path("catalog/presets/", SellerOptionPresetListCreateView.as_view(), name="catalog_preset_list_create"),
    path("catalog/presets/<int:preset_id>/", SellerOptionPresetDetailView.as_view(), name="catalog_preset_detail"),
    path("admin/catalog/providers/", AdminProviderListCreateView.as_view(), name="admin_catalog_provider_list_create"),
    path("admin/catalog/providers/<int:provider_id>/", AdminProviderDetailView.as_view(), name="admin_catalog_provider_detail"),
    path("admin/catalog/categories/", AdminProductCategoryListCreateView.as_view(), name="admin_catalog_category_list_create"),
    path("admin/catalog/categories/<int:category_id>/", AdminProductCategoryDetailView.as_view(), name="admin_catalog_category_detail"),
    path("admin/catalog/filters/", AdminCategoryFilterListCreateView.as_view(), name="admin_catalog_filter_list_create"),
    path("admin/catalog/filters/<int:filter_id>/", AdminCategoryFilterDetailView.as_view(), name="admin_catalog_filter_detail"),
    path("admin/catalog/filter-options/", AdminCategoryFilterOptionListCreateView.as_view(), name="admin_catalog_filter_option_list_create"),
    path("admin/catalog/filter-options/<int:option_id>/", AdminCategoryFilterOptionDetailView.as_view(), name="admin_catalog_filter_option_detail"),
    path("admin/catalog/reference-images/", AdminCategoryReferenceImageListCreateView.as_view(), name="admin_catalog_reference_image_list_create"),
    path("admin/catalog/reference-images/<int:reference_image_id>/", AdminCategoryReferenceImageDetailView.as_view(), name="admin_catalog_reference_image_detail"),
    path("admin/catalog/home-sections/", AdminHomeProductSectionConfigListCreateView.as_view(), name="admin_catalog_home_section_list_create"),
    path("admin/catalog/home-sections/<int:section_id>/", AdminHomeProductSectionConfigDetailView.as_view(), name="admin_catalog_home_section_detail"),
    path("admin/catalog/site-settings/", AdminSiteDisplaySettingView.as_view(), name="admin_catalog_site_settings"),
    path("catalog/home-hero-slides/", HomeHeroSlideListView.as_view(), name="catalog_home_hero_slide_list"),
    path("admin/catalog/home-hero-slides/", AdminHomeHeroSlideListCreateView.as_view(), name="admin_catalog_home_hero_slide_list_create"),
    path("admin/catalog/home-hero-slides/reorder/", AdminHomeHeroSlideReorderView.as_view(), name="admin_catalog_home_hero_slide_reorder"),
    path("admin/catalog/home-hero-slides/<int:slide_id>/", AdminHomeHeroSlideDetailView.as_view(), name="admin_catalog_home_hero_slide_detail"),
    path("admin/catalog/external-categories/", AdminExternalCategoryListCreateView.as_view(), name="admin_catalog_external_category_list"),
    path("admin/catalog/external-attributes/", AdminExternalAttributeListCreateView.as_view(), name="admin_catalog_external_attribute_list"),
    path("admin/catalog/category-mappings/", AdminCategoryMappingListCreateView.as_view(), name="admin_catalog_category_mapping_list_create"),
    path("admin/catalog/category-mappings/<int:mapping_id>/", AdminCategoryMappingDetailView.as_view(), name="admin_catalog_category_mapping_detail"),
    path("admin/catalog/filter-mappings/", AdminFilterMappingListCreateView.as_view(), name="admin_catalog_filter_mapping_list_create"),
    path("admin/catalog/filter-mappings/<int:mapping_id>/", AdminFilterMappingDetailView.as_view(), name="admin_catalog_filter_mapping_detail"),
]
