# Generated by Django 5.2.12 on 2026-03-10 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('source_url', models.URLField(verbose_name='구매 링크')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='정가')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='판매가')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='할인율')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('status', models.CharField(choices=[('active', '진행중'), ('expired', '만료')], default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotdeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
