# Generated by Django 5.2.12 on 2026-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotdeals/', verbose_name='대표 이미지'),
        ),
    ]
