# Generated by Django 5.2.12 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotdeals", "0004_hotdeal_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotdeal",
            name="live_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="라이브 방송 링크"),
        ),
    ]
