# Generated by Django 5.2.12 on 2026-03-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='필터명')),
                ('slug', models.SlugField(blank=True, verbose_name='필터 슬러그')),
                ('filter_type', models.CharField(choices=[('checkbox', '다중 체크'), ('single', '단일 선택'), ('range', '범위형'), ('text', '텍스트')], default='checkbox', max_length=20, verbose_name='필터 타입')),
                ('source_mode', models.CharField(choices=[('manual', '수동'), ('imported', '자동수집'), ('hybrid', '혼합')], default='hybrid', max_length=20, verbose_name='생성 방식')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 여부')),
                ('is_visible', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, verbose_name='외부 카테고리 ID')),
                ('name', models.CharField(max_length=255, verbose_name='외부 카테고리명')),
                ('full_path', models.CharField(blank=True, max_length=500, verbose_name='경로')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='원본 payload')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='수집 시각')),
            ],
            options={
                'ordering': ['provider__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제공자명')),
                ('code', models.SlugField(unique=True, verbose_name='제공자 코드')),
                ('provider_type', models.CharField(choices=[('api', '공식 API'), ('feed', '데이터 피드'), ('crawl', '크롤링')], default='api', max_length=20, verbose_name='연동 방식')),
                ('base_url', models.URLField(blank=True, verbose_name='기본 URL')),
                ('credentials_hint', models.CharField(blank=True, max_length=255, verbose_name='키 관리 메모')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='연동 메타')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='표시명')),
                ('normalized_value', models.CharField(blank=True, max_length=120, verbose_name='정규화 값')),
                ('color_code', models.CharField(blank=True, max_length=20, verbose_name='색상 코드')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.categoryfilter')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=120, verbose_name='외부 속성 키')),
                ('name', models.CharField(max_length=255, verbose_name='외부 속성명')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='원본 payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.externalcategory')),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('category', 'external_key')},
            },
        ),
        migrations.AddField(
            model_name='externalcategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.externalprovider'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='카테고리명')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='카테고리 슬러그')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_visible', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': '내부 상품 카테고리',
                'verbose_name_plural': '내부 상품 카테고리',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='categoryfilter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.productcategory'),
        ),
        migrations.CreateModel(
            name='ExternalAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_value', models.CharField(max_length=255, verbose_name='외부 값')),
                ('normalized_value', models.CharField(blank=True, max_length=255, verbose_name='정규화 값')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='원본 payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.externalattribute')),
            ],
            options={
                'ordering': ['external_value', 'id'],
                'unique_together': {('attribute', 'external_value')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='externalcategory',
            unique_together={('provider', 'external_id')},
        ),
        migrations.CreateModel(
            name='FilterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '기각')], default='pending', max_length=20, verbose_name='승인 상태')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='운영 메모')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_filter_mappings', to=settings.AUTH_USER_MODEL)),
                ('external_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_mappings', to='catalog.externalattribute')),
                ('internal_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='catalog.categoryfilter')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('internal_filter', 'external_attribute')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '기각')], default='pending', max_length=20, verbose_name='승인 상태')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='운영 메모')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_category_mappings', to=settings.AUTH_USER_MODEL)),
                ('external_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_mappings', to='catalog.externalcategory')),
                ('internal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('internal_category', 'external_category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryfilter',
            unique_together={('category', 'slug')},
        ),
    ]
