# Generated by Django 5.2.12 on 2026-03-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='알림 이름')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='저장된 필터 조건')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='추가 키워드')),
                ('notify_events', models.JSONField(blank=True, default=list, verbose_name='알림 이벤트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('last_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 매칭 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='catalog.productcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', '내부 알림'), ('email', '이메일'), ('kakao', '카카오톡'), ('sms', '문자')], max_length=20, verbose_name='알림 채널')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='catalog.productalertsubscription')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('subscription', 'channel')},
            },
        ),
    ]
