# Generated by Django 5.2.12 on 2026-03-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productalertsubscription_subscriptionchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='표시명')),
                ('image', models.ImageField(upload_to='catalog/reference-images/', verbose_name='이미지')),
                ('source_mode', models.CharField(choices=[('manual', '수동'), ('imported', '자동수집')], default='manual', max_length=20, verbose_name='생성 방식')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
