# Generated by Django 5.2.12 on 2026-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categoryreferenceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProductSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='섹션 제목')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='섹션 설명')),
                ('source_type', models.CharField(choices=[('hotdeal', '핫딜'), ('marketplace', '중고장터')], default='marketplace', max_length=20, verbose_name='데이터 소스')),
                ('category_keyword', models.CharField(blank=True, max_length=120, verbose_name='카테고리 키워드')),
                ('item_limit', models.PositiveIntegerField(default=8, verbose_name='노출 개수')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
