# Generated by Django 5.2.12 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_selleroptionpreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeHeroSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, verbose_name="슬라이드 제목")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="슬라이드 설명")),
                ("image", models.ImageField(upload_to="catalog/home-hero-slides/", verbose_name="슬라이드 이미지")),
                ("badge", models.CharField(blank=True, max_length=40, verbose_name="배지")),
                ("href", models.URLField(blank=True, verbose_name="연결 URL")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="정렬 순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "메인 전면 광고",
                "verbose_name_plural": "메인 전면 광고",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
