# Generated by Django 5.2.12 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_create_homeheroslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeheroslide",
            name="display_seconds",
            field=models.PositiveIntegerField(default=3, verbose_name="표시 시간(초)"),
        ),
        migrations.AddField(
            model_name="homeheroslide",
            name="transition_style",
            field=models.CharField(
                choices=[
                    ("next", "깔끔 다음 페이지"),
                    ("slide_lr", "슬라이드 좌우"),
                    ("slide_ud", "슬라이드 상하"),
                    ("fade", "페이드아웃 페이드인"),
                    ("mosaic", "모자이크식 슬라이드전환"),
                ],
                default="next",
                max_length=20,
                verbose_name="전환 방식",
            ),
        ),
    ]
