# Generated by Django 5.2.15 on 2026-06-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_postmalllink'),
        ('catalog', '0012_sync_external_and_hero_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(help_text="클라우드(GCS)에서는 'hero/파일명' 경로로 저장됩니다. Admin에서 이미지 업로드 후 '경로' 링크를 클릭해 실제 파일 위치를 탐색할 수 있습니다.", upload_to='hero/', verbose_name='슬라이드 이미지'),
        ),
        migrations.CreateModel(
            name='HomeBoardSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='섹션 제목')),
                ('columns', models.PositiveSmallIntegerField(choices=[(1, '1열'), (2, '2열'), (3, '3열')], default=1, verbose_name='노출 열 수')),
                ('position', models.CharField(choices=[('left', '좌측'), ('center', '중앙'), ('right', '우측')], default='center', max_length=10, verbose_name='위치')),
                ('content_mode', models.CharField(choices=[('best', '베스트컨텐츠'), ('recent', '최근컨텐츠')], default='recent', max_length=10, verbose_name='컨텐츠 유형')),
                ('item_limit', models.PositiveIntegerField(default=5, verbose_name='노출 개수')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_board_sections', to='boards.board', verbose_name='연결 게시판')),
            ],
            options={
                'verbose_name': '홈 게시판 노출 설정',
                'verbose_name_plural': '홈 게시판 노출 설정',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
