# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_homeheroslide_image_homeboardsectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedisplaysetting',
            name='show_live_menu',
            field=models.BooleanField(default=False, verbose_name='방송 메뉴 노출'),
        ),
    ]
