# Generated by Django 5.2.12 on 2026-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='정지 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='operator_role',
            field=models.CharField(choices=[('none', '일반회원'), ('moderator', '운영자'), ('admin', '관리자'), ('superadmin', '최고관리자')], default='none', max_length=20, verbose_name='운영 권한'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspend_count',
            field=models.PositiveIntegerField(default=0, verbose_name='누적 정지 횟수'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspend_public',
            field=models.TextField(blank=True, verbose_name='정지 공개 사유'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspend_reason',
            field=models.TextField(blank=True, verbose_name='정지 운영 메모'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspend_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='정지 해제일'),
        ),
    ]
