# Generated by Django 5.2.12 on 2026-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('buyer', '구매자'), ('seller', '판매자')], default='buyer', max_length=20, verbose_name='회원 타입'),
        ),
    ]
