# Generated by Django 5.2.12 on 2026-03-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=120, unique=True, verbose_name='주문번호')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='결제 금액')),
                ('currency', models.CharField(default='KRW', max_length=10, verbose_name='통화')),
                ('provider', models.CharField(default='portone', max_length=50, verbose_name='PG사')),
                ('payment_key', models.CharField(blank=True, max_length=120, verbose_name='결제 키')),
                ('status', models.CharField(choices=[('pending', '결제대기'), ('paid', '결제완료'), ('failed', '결제실패'), ('cancelled', '결제취소')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('marketplace_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.marketplaceitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
