# Generated by Django 5.2.12 on 2026-03-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOARD_CREATE', '게시판 생성'), ('BOARD_DELETE', '게시판 삭제'), ('BOARD_HIDE', '게시판 숨김'), ('POST_DELETE', '게시글 삭제'), ('POST_BLIND', '게시글 블라인드'), ('POST_MOVE', '게시글 이동'), ('USER_SUSPEND', '회원 정지'), ('USER_UNSUSPEND', '회원 정지해제'), ('USER_GRADE', '등급 변경'), ('USER_POINT', '포인트 조정'), ('IP_BAN', 'IP 차단'), ('REPORT_HANDLE', '신고 처리')], max_length=30, verbose_name='행동 유형')),
                ('target_id', models.PositiveIntegerField(verbose_name='대상 ID')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='상세 정보')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='처리 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
