# Generated by Django 5.2.12 on 2026-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('BOARD_CREATE', '게시판 생성'), ('BOARD_DELETE', '게시판 삭제'), ('BOARD_HIDE', '게시판 숨김'), ('POST_DELETE', '게시글 삭제'), ('POST_BLIND', '게시글 블라인드'), ('POST_MOVE', '게시글 이동'), ('USER_SUSPEND', '회원 정지'), ('USER_UNSUSPEND', '회원 정지해제'), ('USER_GRADE', '등급 변경'), ('USER_POINT', '포인트 조정'), ('IP_BAN', 'IP 차단'), ('KEYWORD_FILTER', '금칙어 관리'), ('REPORT_HANDLE', '신고 처리')], max_length=30, verbose_name='행동 유형'),
        ),
    ]
